[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--prefer-offline --no-audit"
  CI = "true"
  ROLLUP_IGNORE_NATIVE = "false"
  # Environment variables for build (set these in Netlify dashboard)
  GEMINI_API_KEY = ""
  EMAILJS_SERVICE_ID = ""
  EMAILJS_TEMPLATE_ID = ""
  EMAILJS_PUBLIC_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
